### ISSUE TITLE
New rsnapshot release 1.4.3

### ISSUE THREAD

**Issue by gratuxri** [MTecknology/rsnapshot#1]
Hello,

after git pull on rsnapshot project, I was really impressed, that rsnapshot released new version 1.4.3 in git tags. I have build this package with some other changes on debian branch (https://salsa.debian.org/gratuxri-guest/rsnapshot). What do you think about collaboration on build rsnapshot packages and fixing bugs on salsa.debian.org ?

**Comment by MTecknology** [comment]
To put the "salsa" topic bluntly- I have interest in working with that giant mess as little as possible (for reasons that can be found on the mailing list).

I'm happy to collaborate with this package via github. I notice that we made many of the same changes in regard to 1.4.3-1. One major change with your repository is that the 'debian' branch no longer has just debian packaging; it's now a copy of all source data. That makes the diff for your single commit /very/ large.

Note- I don't plan to keep this packaging repo here. It's a temporary location while other things with rsnapshot are worked out.

If you have a vested interest in rsnapshot, it's worth checking out the open issues against rsnapshot. It's in need of strong developers to help squash many bugs.

As far as releasing 1.4.3-1 goes- I'm running into an issue with tests in `t/ssh_args/ssh_args.t`. I'd like to resolve that before uploading a new package version. I would also like to see these resolved before uploading:
- https://github.com/rsnapshot/rsnapshot/issues/191
- https://github.com/rsnapshot/rsnapshot/issues/242

Feel free to reach out to me on freenode/oftc if you'd like to chat further.

**Comment by MTecknology** [comment]
I changed my mind on the tests. They sound nice, but they also require a very special testing environment, which isn't something our build system should plan to provide.

**Comment by MTecknology** [comment]
@gratuxri I sent you an invite to the new repository location. I made an attempt to clean things up and conform to more standard packaging practices. Feel free to prod me on IRC.

I will be deleting this repository in the near future.
